services:

  app:
    build: .

    ports:
      - "8080:8080"

    depends_on:
      - mysql

  mysql:
    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: Sonal@123
      MYSQL_DATABASE: fitness

    ports:
      - "3307:3306"